/* Generated By:JavaCC: Do not edit this line. DnParserImplConstants.java */
package org.springframework.ldap.core;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DnParserImplConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ALPHA = 1;
  /** RegularExpression Id. */
  int DIGIT = 2;
  /** RegularExpression Id. */
  int LEADCHAR = 3;
  /** RegularExpression Id. */
  int STRINGCHAR = 4;
  /** RegularExpression Id. */
  int TRAILCHAR = 5;
  /** RegularExpression Id. */
  int SPECIAL = 6;
  /** RegularExpression Id. */
  int HEXCHAR = 7;
  /** RegularExpression Id. */
  int HEXPAIR = 8;
  /** RegularExpression Id. */
  int BACKSLASHCHAR = 9;
  /** RegularExpression Id. */
  int PAIR = 10;
  /** RegularExpression Id. */
  int ESCAPEDSTART = 11;
  /** RegularExpression Id. */
  int QUOTECHAR = 12;
  /** RegularExpression Id. */
  int HASHCHAR = 13;
  /** RegularExpression Id. */
  int ATTRIBUTE_TYPE_STRING = 14;
  /** RegularExpression Id. */
  int LDAP_OID = 15;
  /** RegularExpression Id. */
  int SPACE = 16;
  /** RegularExpression Id. */
  int ATTRVALUE = 17;
  /** RegularExpression Id. */
  int SPACED_EQUALS = 18;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int ATTRVALUE_S = 1;
  /** Lexical state. */
  int SPACED_EQUALS_S = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<ALPHA>",
    "<DIGIT>",
    "<LEADCHAR>",
    "<STRINGCHAR>",
    "<TRAILCHAR>",
    "<SPECIAL>",
    "<HEXCHAR>",
    "<HEXPAIR>",
    "\"\\\\\"",
    "<PAIR>",
    "<ESCAPEDSTART>",
    "\"\\\"\"",
    "\"#\"",
    "<ATTRIBUTE_TYPE_STRING>",
    "<LDAP_OID>",
    "\" \"",
    "<ATTRVALUE>",
    "<SPACED_EQUALS>",
    "\",\"",
    "\";\"",
    "\"+\"",
  };

}
